### ISSUE TITLE
Do you have any plans to upgrade on Vendure 2.0.0

### ISSUE THREAD

**Issue by Eusebiotrigo** [mirahi-io/vendure-adyen-dropin-plugin#1]
Hi, 
Do you have any plans to upgrade the plugin so it works with Vendure 2.0.0?

**Comment by NicoToff** [comment]
Hi @Eusebiotrigo!
I'm on holidays right now and my company is still using pre-v2. We love Vendure and consider Adyen as our payment provider, so there's a good chance I'll upgrade the plugin, but not before August, unfortunately.

**Comment by Eusebiotrigo** [comment]
Great! Thanks for answering!
I will give it a try to upgrade on our side and possibly raise a PR if you agree and we are able to make it work 😉
